work day:
    cargo watch -w {{day}} -x "check -p {{day}}" -s "just test {{day}}" -s "just lint {{day}}"

lint day:
    cargo clippy -p {{day}}

test day:
    cargo nextest run -p {{day}} 

create day:
    cargo generate --path ./template --name {{day}}
